### PR TITLE
Format descriptions with markdown

### PR DESCRIPTION
**Pull request by cthoyt**
This PR adds formatting for the description of resources and collections with markdown. However, it only enables markdown formatting to descriptions of resources directly curated in the Bioregistry (i.e., it won't allow this if the data was imported from an external resource) to make sure nobody does anything sneaky

### CODE REVIEW

**Comment by dhimmel** [comment]
Missing dependency:

```
ModuleNotFoundError: No module named 'markupsafe'
```

**Comment by cthoyt** [comment]
> Missing dependency:
> 
> ```
> ModuleNotFoundError: No module named 'markupsafe'
> ```

Oh no I thought this was a transitive dependency of flask

**Comment by dhimmel** [comment]
Any chance we could get a fix, I'm stuck waiting on an "Update Data" build to pass with the latest Bioregistry? Let me know if you'd like a PR.

**Comment by cthoyt** [comment]
Hi @dhimmel thanks for being patient, I was on holiday. The fix is issued in 1a2ef71

**Pull request merged**
