### PR TITLE
Run new prefix requests after debugging

### LINKED ISSUE #1110: Add prefix uniprot.mnemonic
### Prefix

uniprot.mnemonic

### Name

UniProt

### Homepage

https://www.uniprot.org/

### Source Code Repository

_No response_

### Description

The UniProt Knowledgebase (UniProtKB) is a comprehensive resource for protein sequence and functional information with extensive cross-references to more than 120 external databases. Besides amino acid sequence and a description, it also provides taxonomic data and citation information.

This entry represents UniProt mnemonics which combine an alphanumeric representation the protein name and a species identification code representing the biological source of the protein.

### License

_No response_

### Publications

pubmed:16381842

### Example Local Unique Identifier

BRAF_HUMAN

### Regular Expression Pattern for Local Unique Identifier

^[A-Z0-9]{1,10}_[A-Z0-9]{1,5}$

### URI Format String

https://www.uniprot.org/uniprotkb/$1

### Wikidata Property

_No response_

### Contributor Name

Benjamin M. Gyori

### Contributor GitHub

bgyori

### Contributor ORCiD

0000-0001-9439-5346

### Contributor Email

b.gyori@northeastern.edu

### Contact Name

_No response_

### Contact ORCiD

_No response_

### Contact GitHub

_No response_

### Contact Email

_No response_

### Additional Comments

_No response_

### LINKED ISSUE #1146: Add prefix fda.application
### Prefix

fda.application

### Name

FDA Application

### Homepage

https://fda.report/applications

### Source Code Repository

_No response_

### Description

This prefix is for FDA application identifiers. There are multiple types of FDA applications (https://www.fda.gov/drugs/how-drugs-are-developed-and-approved/types-applications), including New Drug Application (NDA). FDA.report provides access to all FDA databases, including applications, in a single portal, and can resolve FDA application identifiers.

### License

_No response_

### Publications

_No response_

### Example Local Unique Identifier

070886

### Regular Expression Pattern for Local Unique Identifier

^\d{6}$

### URI Format String

https://fda.report/applications/$1

### Wikidata Property

_No response_

### Contributor Name

Benjamin M. Gyori

### Contributor GitHub

bgyori

### Contributor ORCiD

0000-0001-9439-5346

### Contributor Email

b.gyori@northeastern.edu

### Contact Name

_No response_

### Contact ORCiD

_No response_

### Contact GitHub

_No response_

### Contact Email

_No response_

### Additional Comments

The official FDA website doesn't appear to be able to resolve application IDs but these IDs do appear in some PDF documents, e.g., https://www.fda.gov/media/159183/download.

### PR DESCRIPTION
**Pull request by bgyori**
It turns out that if there are any open GitHub issues with the New / Prefix tags and they contain some invalid data, _all_ new prefix issue processing fails before being committed and pull requested. After untagging a problematic issue, the new prefix code runs, the result of which is this PR.

Closes #1146, Closes #1110

### CODE REVIEW

**Comment by lubianat** [comment]
@bgyori sorry for the terrible delay! It is the first thing I'll do tomorrow morning.

**Comment by bgyori** [comment]
Yes, these are just two regular new prefix request additions. Looks like there is a conflict with the latest main now which I will fix and push in a minute. The tests fail just because these kinds of PRs require a `reviewer`'s info to be added to the new prefix in bioregistry.json. Once you add your info there and push, the tests will pass. See also here about how this works: https://github.com/biopragmatics/bioregistry/pull/1150#issuecomment-2246641516

**Comment by lubianat** [comment]
As I do not have write access, I opened a PR for this PR, hopefully that is the correct workflow. 

I saw that the uniprot.mnemonic prefix had a bit of a discussion related to scope. I assume the decision was to ingest it any way, right? Even though it is not a _de jure_ identifier. Should there be a comment or some kind of flag highlighting they are possibly not stable?

**Comment by bgyori** [comment]
@lubianat thanks for looking at this! I actually didn't realize until now but the reviewer team, including you only had `triage` permissions. I changed that to `write` since (as far as I understand) that will allow you and others doing reviews to push to PRs. If not, then we can refine things further.

To respond you your questions:
- I saw that the uniprot.mnemonic prefix had a bit of a discussion related to scope. I assume the decision was to ingest it any way, right? Even though it is not a de jure identifier. 

Yes, this is a bit controversial but I decided to include it as a net positive. Mnemonics are used widely in various data sets and knowledgebases and so from a data integration perspective, having metadata on, and being able to validate and resolve mnemonics is a good feature.

- Should there be a comment or some kind of flag highlighting they are possibly not stable?

This could be a more general feature in Bioregistry, we can open a separate issue.

**Comment by lubianat** [comment]
Thanks for the clarification! I'll wait for the tests to run, and then we should be good to go.

**Comment by bgyori** [comment]
@lubianat for future reference, bioregistry.json has a fixed JSON style (e.g., alpabetical ordering of keys) that tests look at. An automated way to lint files to make sure they will pass tests is
```
tox -e bioregistry-lint
```
For instance, in this case, this changed the order of the `reviewer` and `url_pattern` keys to be alphabetical, which I just pushed.

**Pull request merged**
