### PR TITLE
Update license for sphn

### PR DESCRIPTION
**Pull request by deepakunni3**
This is a PR to update the license for the SPHN

@cthoyt Let me know if there is anything else I need to update as part of the PR

### CODE REVIEW

**Comment by cthoyt** [comment]
It would be informative to attach an email to your contributor information - is there one that you're okay with being public? Otherwise this is great, another dataset gets its wings!

**Comment by deepakunni3** [comment]
oh yes, of course! Just added the email 👍

**Comment by cthoyt** [comment]
Thanks! Will merge after lunch

**Comment by deepakunni3** [comment]
Thank you for fixing the tests. Was trying locally to see what was the issue.

Much appreciated :)

**Pull request merged**
