### PR TITLE
Add prefixes for taxonomy resources listed in Wikidata

### LINKED ISSUE #396: [new prefixes] add more taxonomic resources
As discussed,

I am opening an issue to improve the coverage of the Bioregistry for taxonomic databases prefixes.

A good starting point would be:

https://www.wikidata.org/wiki/Wikidata:WikiProject_Taxonomy#Databases

@cthoyt There are many, if you need a priority list, I could start by doing a ranked list dependent on the number of items with taxonomic DB identifiers on Wikidata.

A huge advantage is that for each listed DB, the related property has already the formatted URL described, etc. See https://www.wikidata.org/wiki/Property_talk:P9157 for an example.

Happy to elaborate and help where I can!

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #396

Based on the suggestion from @Adafede, this PR does the following:

- [x] Gets a list of Wikidata properties corresponding to taxonomy databases/vocabularies
- [x] Gets related metadata from Wikidata
- [x] Curates and generates Bioregistry records for these taxonomy databases/vocabularies

Follow progress in [this Jupyter notebook](https://nbviewer.org/github/biopragmatics/bioregistry/blob/wikidata-taxonomy-import/Bioregistry%20Taxonomy%20Curation%20via%20Wikidata.ipynb).

Priority should go to making prefixes available for resources mapped by lotus, so https://github.com/lotusnprod/lotus-web/pull/25 can be extended to make more useful link-outs using the Bioregistry (e.g., see the "Organism taxonomy" section of https://lotus.naturalproducts.net/compound/lotus_id/LTS0160430 - so focus on iNaturalist, Open Tree of Life, and other ones in https://github.com/lotusnprod/lotus-web/blob/07441c0c2d962c7b3181dce74631ccbe5b1796cf/src/main/js/components/compoundcard/TaxonomyReferenceMap.js#L153-L187)

### CODE REVIEW

**Comment by cthoyt** [comment]
cc @megbalk

**Comment by megbalk** [comment]
Fossilworks ID for this taxon
Fossilworks ID for this journal article
- I am not sure this website is functional still. I'd use fossilworks as the id, however.

WoRMS-ID for taxa
- I'd use worms

Catalogue of Life ID
Catalogue of Life in Taiwan ID
- I'd use col with col.country for others

Open Tree of Life ID
-I'd use open.tol

Tree of Life Web Project ID
- I'd use tol.webproj

NOAA Fisheries Species Directory ID
- I'd use noaa

**Comment by cthoyt** [comment]
@megbalk do you want to go ahead and make some new prefix requests for those?

**Comment by megbalk** [comment]
@cthoyt sure! I will attempt to do that!

**Comment by Adafede** [comment]
🚀

**Comment by cthoyt** [comment]
@Adafede they're not all in but we made some nice progress and I think the notebook is a good place for doing some follow-up to finish this up

**Pull request merged**
