### PR TITLE
Update Wikipathways description and license

### PR DESCRIPTION
**Pull request by egonw**
Per suggestion here: https://github.com/identifiers-org/identifiers-org.github.io/issues/205

### CODE REVIEW

**Comment by egonw** [comment]
(sorry, stupid Kate...)

**Comment by cthoyt** [comment]
However, before merging, I'd suggest improving the descriptive text here further.

**Comment by egonw** [comment]
> note that we store the MIRIAM data but do not update it ourselves. 

Yes, that's what I meant when I said would it not be overwritten :( and why I had not created that pr until you asked :(

**Comment by cthoyt** [comment]
No problem though, check the diff for the solution!

**Pull request closed without merging**
