### PR TITLE
Adding NFDI4Chem collection

### PR DESCRIPTION
**Pull request by StroemPhi**
This PR adds the NFDI4Chem collection to the Bioregistry.

### CODE REVIEW

**Comment by cthoyt** [comment]
Hi @StroemPhi, thanks for the contribution! As you can see from the unit tests, there are a few prefixes listed here that aren't valid bioregistry prefixes:

- ssnsystem
- sosa
- oboe
- ssn
- nmrcv
- vibso

I can support you to add these prefixes, or you can move them into the description with some information that there's a bit of extra work to do.

**Comment by StroemPhi** [comment]
All but vibso should be added imho. Let me have a try with ssnsystem and then I/we can see how good I manage, bofore I'll add the other ones. And VIBSO is not yet registered properly as it is still WIP. So that would be a case of prefix-parking, right?

**Comment by cthoyt** [comment]
VIBSO is fine to add - because there's a public artifact at https://github.com/NFDI4Chem/VibrationalSpectroscopyOntology it's not considered prefix parking

**Comment by cthoyt** [comment]
Note that ontokin is registered under https://bioregistry.io/registry/worldavatar.kin

**Review by cthoyt — APPROVED** [review]

**Pull request merged**
