### PR TITLE
change `nmdc` url (and relax pattern)

### PR DESCRIPTION
**Pull request by dwinston**
Use w3id.org resolver as first-redirect entrypoint

microbiomedata/issues#423

/cc @turbomam @aclum

### CODE REVIEW

**Comment by cthoyt** [comment]
@dwinston did you see that there is already a `nmdc` entry in the JSON? can you try and put your changes inside the existing record instead of making a new one?

**Comment by dwinston** [comment]
oh that's so weird, I thought that's precisely what I did, but I can see from the diff that it got saved as an addition. sorry about that. will fix.

**Comment by cthoyt** [comment]
@dwinston I see the issue - you have not updated your branch wrt the origin. It's also the case that you haven't enabled me to push to your branch, so I can't update this myself

**Comment by cthoyt** [comment]
@dwinston FYI I isolated the relevant change in #982, and will close this PR in favor of that one

**Comment by dwinston** [comment]
thank you, @cthoyt.

**Pull request closed without merging**
